### ISSUE TITLE
Accessing a public repository after configuring an access token results in 401 unauthorized error

### ISSUE THREAD

**Issue by suoto** [danielboucek/private-extensions-gitlab#2]
I setup this extension on a repository whose visibility was initially set to "internal". I created an access token on GitLab and configured it on VS Code and it worked just fine.

I then changed the repository's visibility to "public" and revoked the access token, and the extension now fails to fetch GitLab packages because the request fails with error code 401.

I can work around this by setting the access token to ` ` (an empty white space).

I deleted `~/.vscode` in an attempt to reset the stored access token but that didn't work, so maybe the extension could have a command to delete the existing access token?

Also, might be interesting if the extension tried to access GitLab without the access token (i.e., consider the packages as public) and, in case this returns 401, try accessing with the token.

**Comment by danielboucek** [comment]
GitLab checks the validity of the token even if it is not needed so I will add an option to remove the stored access token.

Currently the extension does not allow you to make request without the token so I will change that. If the token is not set it will make a request in case it return 401 it will tell you to set a token. If token is set it will always use that token. 
If you have set a token I assume that the token is valid and you need it for the requests.

This should fix any issues that you have, if you want to have the repository set to 'public'. It will be available in the next version soon.

**Comment by danielboucek** [comment]
Due to security reasons I was unable to properly determine if project needs an authentication or not.
The best solution for now is to set the access token to single white-space (Added in readme), The extension is primarily meant to be used with an access token.
